read_csv("USvideos")
data.frame(USvideos)
as.Date(USvideos$trending_date,"%y.%d.%m")
library("tidyverse")
USvideos %>% separate(col="publish_time",into=c("PDate","PTime")," ")
as.Date(USvideos$PDate, "%y.%m.%d")
str_to_lower(USvideos$title, locale = "en")
str_to_title(USvideos$title, locale = "en")
View(USvideos)
as.POSIXct(USvideos$publish_time, tz = "EST")
View(USvideos)
